### ISSUE TITLE
MacOS support?

### ISSUE THREAD

**Issue by arnaudWasappli** [willpowell8/LocalizationKit_iOS#5]
At least for String part...

**Comment by willpowell8** [comment]
@arnaudWasappli really good idea. I have modified the library so that it can now work for iOS and Mac OSX from the same library. This is only first iteration but I will build it out more.

I have also added support for **NSTextField** as well as **String**

Annoyingly I labeled the repo LocalizationKit_iOS which I may need to change as it now supports MacOSX.
